### PR TITLE
Fix thresholds setting in AddCosigner

### LINKED ISSUE #13: Thresholds not set on dev user account
I created a user for a dev DApp:
```
mobius-cli create dapp-account -a GBDDAMWGPB7ZCOJPM2XANNNQDII7QQIQNN7XMQXG32CE44DORVYJC6HP
```

This is the account it created. All thresholds are zero: https://testnet.steexp.com/account/GBEV5ZUNURIPM25G3SM2LFDNMNXSU56Z6HMM37C2PT3TVDTPNEWWNWDX#signing

But looking at a dapp authorized user account on mainnet I see Low: 1 Med: 1 High: 10 ..   For example this one created for StellarBall app: https://steexp.com/account/GCSDPHHGYBUM3QOCV6ZY7NVZH5AYC7ICIV7IVC7SOF4M2R3RB2D65RPP#signing  Which makes sense, blocking the DApp from changing signers etc.

### PR DESCRIPTION
**Pull request by nebolsin**
Set Options operation can either set the values, or add/remove a signer, not both.

- [x] Fix threshold configuration in `Mobius::Client::Blockchain::AddCosigner`
- [x] Configure thresholds using `cosigner_weight` and `master_weight` parameters

Closes #13.

### CODE REVIEW

File: lib/mobius/client/blockchain/add_cosigner.rb [hunk 1]
```diff
@@ -3,20 +3,23 @@ class Mobius::Client::Blockchain::AddCosigner
...
   # @param cosigner_keypair [Stellar::Keypair] Cosigner account keypair
-  # @param weight [Integer] Cosigner weight, default: 1
+  # @param cosigner_weight [Integer] Cosigner weight, default: 1
+  # @param master_weight [Integer] Master key weight, default: 10
   # @!scope instance
   param :keypair
   param :cosigner_keypair
-  param :weight, default: -> { 1 }
+  param :cosigner_weight, default: -> { 1 } # TODO: should be an option too
+  option :master_weight, default: -> { 10 }
```
Comment (gzigzigzeo) [inline lib/mobius/client/blockchain/add_cosigner.rb]: I think, as long as we stay above 4 params/constructor and that params are vital indeed, master_weight could also be the param, not an option

File: lib/mobius/client/blockchain/add_cosigner.rb [hunk 2]
```diff
@@ -30,22 +33,36 @@ def call
...
-      signer: signer,
-      master_weight: 10,
-      highThreshold: 10,
-      medThreshold: 1,
-      lowThreshold: 1
+      sequence: account.next_sequence_value
+    ).tap do |txn|
+      txn.operations << add_cosigner_op
+      txn.operations << set_thresholds_op
+      txn.fee *= txn.operations.size
```
Comment (gzigzigzeo) [inline lib/mobius/client/blockchain/add_cosigner.rb]: That might be fixed already in stellar-base

Comment (nebolsin) [reply lib/mobius/client/blockchain/add_cosigner.rb]: I don’t think so. AFAIK It is implemented in js-stellar-base, but not in ruby-stellar-base
